### ISSUE TITLE
TustDNS needs update 

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#310]
https://users.rust-lang.org/t/rustsec-advisory-for-trust-dns-proto-affecting-server-resolver-and-client/21179

deadline:10/22/18

**Comment by drozdziak1** [comment]
Deadline set to **by Friday**

**Comment by drozdziak1** [comment]
To cite the link:
```
This has been fixed in the current release of trust-dns-proto 0.4.3 41, which aligns with the trust-dns-resolver 0.9 release, as well as trust-dns (client) and trust-dns-server 0.14 series.
```

Here's an excerpt of today's rita/Cargo.toml:
```toml
tokio-io = "0.1.8"
tokio-codec = "0.1.0"
regex = "1.0.5"
trust-dns-resolver = "0.9.1" # above 0.9
handlebars = "1.0.3"
byteorder = { version = "1.2.6", features = ["i128"] }
```
